<?php

?>

<script type="text/javascript">
var cwc_initial_entity_id = 1;
var topMenu = [];
var leftMenu = [];
topMenu.push(
    {
        text    : 'Транзакции',
        //iconCls : 'settings-ico',
        href       : '/#transaction/index',
        hrefTarget : "_self" 
    }
);
</script>
<script type="text/javascript" src="/js/index/base.js"></script>
<script type="text/javascript" src="/js/index/app.js"></script>