<?php echo $this->doctype(); ?>
<html>
<head>
    <title>ciwic</title>
    <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
 
    <link rel="stylesheet" type="text/css" href="/js/extjs/resources/css/ext-all-neptune.css" />

    <script type="text/javascript" src="/js/extjs/ext-all-dev.js"></script>
    <script type="text/javascript" src="/js/extjs/ext-theme-neptune.js"></script>

    <script type="text/javascript" src="/js/extjs/locale/ext-lang-ru.js"></script>
    <script type="text/javascript" src="/js/index/plugins/GridHeaderFilters.js"></script>
	 
</head>
<body>
<form method="get" action="" class="x-hidden" target="_blank" id="fakeForm"><input type='hidden' name='data' value='' /><input type='hidden' name='filename' value='' /></form>
<?php echo $this->content; ?>
</body>
</html>